name: Exercice 1 - mon premier workflow GitHub Actions

on: [push] #

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: 1) Message de bienvenue
        run: echo "Bienvenue dans mon premier workflow GitHub Actions !"

      - name: 2) Afficher la date du système
        run: date

      - name: 3) Afficher le répertoire courant
        run: pwd

      - name: 4.a) Checkout du code source
        uses: actions/checkout@v5

      - name: 4.b) Lister les fichiers du projet
        run: ls -al
